server:
  port: 8081

spring:
  application:
    name: BFF


recursos:
  service:
    url: http://localhost:8083 # El Microservicio 2 (Recursos) correrá en el 8083

proyectos:
  service:
    url: http://localhost:8084 # El Microservicio 1 (Proyectos) corre en el 8082


resilience4j:
  circuitbreaker:
    instances:
      proyectosCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
      recursosCB:
        slidingWindowSize: 10
        failureRateThreshold: 50